name: dropthebeat App CI/CD
on:
  push:
    branches:
      - main
env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET_NAME: hackton.choilab.xyz

jobs:
  build:
    name: Deploy to Develop
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      packages: write
      contents: read
      id-token: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Build install app
        run: yarn run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dropthebeat
          path: app

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dropthebeat
          path: app

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync app/ s3://${{ env.AWS_S3_BUCKET_NAME }}/